name: phasmophobiaevidence
description: phasmophobiaevidence

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: any
  shared_preferences : any
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ghostEntries.json